### PR TITLE
fix #14

### LINKED ISSUE #14: Person endpoint is erroring out
```json
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Date: Tue, 01 Dec 2015 20:53:17 GMT
Status: 500 Internal Server Error
X-Content-Type-Options: nosniff
Content-Length: 94
Connection: Close
 {
  "error": {
    "type": "api_error",
    "message": "Sorry, something went wrong. We have been notified."
  }
}
```

### PR DESCRIPTION
**Pull request by jgrayson676**

### CODE REVIEW

File: src/person_lookup.coffee [hunk 1]
```diff
@@ -11,7 +11,7 @@ handle = (vars, callback) ->
 
   result = {}
 
-  clearbit.Person.find({email: vars.lead.email, stream: true}).then((data) ->
+  clearbit.Person.find({email: vars.lead.email.valueOf(), stream: true}).then((data) ->
```
Comment (cgrayson) [inline src/person_lookup.coffee]: Could we get test coverage to ensure this fixes the problem?

File: src/company_lookup.coffee [hunk 2]
```diff
@@ -105,12 +105,16 @@ responseVariables = ->
...
-  if(website.indexOf('http') > -1)
-    return url.parse(website).hostname
+
+createRequest = (email, website) ->
+  if website
+    parsed = url.parse(website.valueOf())
+    if parsed.protocol
+      return {domain: parsed.hostname, stream: true}
+    else
+      return {domain: website, stream: true}
```
Comment (cgrayson) [inline src/company_lookup.coffee]: Doesn't `website` need `valueOf()` here?

**Comment by cgrayson** [comment]
:ok_hand:
